### ISSUE TITLE
2024-07-30 - Make Jekyll Collection for Palette Colors

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/genart#130]
# Description

Turn the sets of `PaletteColor` documentation files into Jekyll collections.

Documentation for collections can be found on the [Jekyll website](https://jekyllrb.com/docs/collections/).

# Tasks

- [x] create the jekyll palette colors collection
- [x] create an example color with front matter, content, and tags
- [x] ~~create an example colors by hex page (color block and code example)~~
- [x] create an example colors by luminance page
- [x] test with multiple colors
- [x] test with multiple color categories
- [x] create all color files
  - [x] black
  - [x] blue
  - [x] brown
  - [x] gray
  - [x] green
  - [x] pink
  - [x] purple
  - [x] red
  - [x] white
- [x] update links in palette color collection documentation
  - [x] palette color maps
    - [x] black
    - [x] blue
    - [x] brown
    - [x] gray
    - [x] green
    - [x] pink
    - [x] purple
    - [x] red
    - [x] white 
- [x] update add new color instructions
