### ISSUE TITLE
color palette: relaxed elegance

### ISSUE THREAD

**Issue by azurepolarbear** [brittni-and-the-polar-bear/genart#208]
palette source: [pantone color of the year: 2025](https://www.pantone.com/color-of-the-year/2025)

# Tasks

- [ ] `rgb(240, 240, 230)` - cannoli cream
- [ ] `rgb(227, 199, 185)` - cream tan
- [ ] `rgb(187, 170, 147)` - safari
- [ ] `rgb(194, 158, 138)` - sirocco
- [ ] `rgb(163, 119, 102)` - mocha mousse
- [ ] `rgb(161, 135, 120)` - chanterelle
- [ ] `rgb(138, 100, 91)` - baltic amber
- [ ] `rgb(86, 69, 64)` - chocolate martini
- [ ] implement palette
