### ISSUE TITLE
Feature Request - 2024-06-01 - String Validator

### ISSUE THREAD

**Issue by azurepolarbear** [brittni-and-the-polar-bear/genart#91]
# Description

We want to add a `StringValidator` class.  The only methods right now will be confirming that something is a valid RGB hex string (#RRGGBB) or a valid RGBA hex string (#RRGGBBAA).

The logic for these checks already exist in the unit tests (`/src/test/shared/color.ts`: `checkForValidHexColorString(hex: string)`.

# Tasks

- [x] create class
- [x] implement valid RGB hex string check
- [x] test valid RGB hex string check
- [x] implement valid RGBA hex string check
- [x] test valid RGBA hex string check

**Comment by blwatkins** [comment]
This item is staged. Development is complete and this feature will be included in the next release.
